const test = require('tape');
const dateFormat = require('dateformat');
const assignment = require('../lib/assignment');

let id;
let now = new Date();
let course = process.env.CANVAS_API_TEST_COURSE_ID;
let createParams = {
  assignment: {
    name: 'Canvas API - Test Suite Assignment',
    integration_id: 'EXAMPLE_ID_123',
    submission_types: 'online_text_entry',
    points_possible: 100,
    grading_type: 'points',
    due_at: dateFormat(now.setDate(now.getDate() + 7), 'isoUtcDateTime'),
    lock_at: dateFormat(now, 'isoUtcDateTime'),
    unlock_at: dateFormat(now.setDate(now.getDate() + 1), 'isoUtcDateTime'),
    description: '<p>This is an example assignment generated by the <strong>canvas-api</strong> module, which has now been edited.</p><p>For more information, please visit: <a href="https://www.npmjs.com/package/canvas-api"target="_blank">https://www.npmjs.com/package/canvas-api</a></p>',
    muted: true,
    published: false
  }
};
let editParams = {
  assignment: {
    name: 'Canvas API - Test Suite Assignment (Edited)',
    description: 'This is an example assignment generated by the canvas-api module, which has now been edited.'
  }
};

test('Assignment - Create', (t) => {
  t.plan(1);
  assignment.create(course, createParams, (error, results) => {
    if (error) {
      t.fail(error.statusCode);
    } else {
      id = results.body.id;
      t.ok(typeof results.body.id, 'number');
    }
  });
});

test('Assignment - Edit', (t) => {
  t.plan(1);
  assignment.edit(course, id, editParams, (error, results) => {
    if (error) {
      t.fail(error.statusCode);
    } else {
      t.ok(results.body.name, editParams.assignment.name);
    }
  });
});

test('Assignment - Get', (t) => {
  t.plan(1);
  assignment.get(course, id, (error, results) => {
    if (error) {
      t.fail(error.statusCode);
    } else {
      t.ok(results.body.name, editParams.assignment.name);
    }
  });
});

test('Assignment - Delete', (t) => {
  t.plan(1);
  assignment.delete(course, id, (error, results) => {
    if (error) {
      t.fail(error.statusCode);
    } else {
      t.ok(typeof results.body.id, id);
    }
  });
});
